// ESLint, flat config.
//
// `next lint` is deprecated and removed in Next 16, so the script calls the ESLint
// CLI directly and this file is the whole configuration. `next/core-web-vitals`
// brings the React, hooks and Next rules; `next/typescript` adds the
// TypeScript-aware ones. FlatCompat is how those two shareable configs, still
// written in eslintrc form, are consumed here.

import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "public/**",
      // Generated by the build, and not ours to lint.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // The codebase uses `any` in a few places where a third-party shape is
      // genuinely unknown. Visible, not fatal.
      "@typescript-eslint/no-explicit-any": "warn",
      // A leading underscore means "deliberately unused", which this codebase uses
      // for discarded destructuring and required-but-ignored parameters.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    // Test files mock modules and assert on loose shapes.
    files: ["**/__tests__/**", "tests-e2e/**", "*.config.*"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
];

export default config;
