// Auto-layout places every edge source strictly left of its target
//
// Generates random directed acyclic graphs and asserts that `autoLayout`
// assigns x-coordinates such that every edge (u, v) satisfies x[u] < x[v].
//
// DAGs are generated by sampling a topological order first and only
// emitting edges from lower-indexed nodes to higher-indexed ones, which
// guarantees acyclicity by construction.
//

import { describe, expect, it } from "vitest";
import fc from "fast-check";
import type { GraphEdge, GraphNode } from "../build";
import { NODE_TYPE } from "../build";
import { autoLayout } from "../layout";

/** Build a `source-container` GraphNode with the given id at origin. */
function makeNode(id: string): GraphNode {
  return {
    id,
    type: NODE_TYPE.sourceContainer,
    data: {
      kind: "source-container",
      entity: {
        id,
        name: id,
        path_prefix: `raw/${id}/`,
        schema: [{ name: "c", type: "string" }],
      },
    },
    position: { x: 0, y: 0 },
  };
}

/**
 * Generate a DAG as `{ nodes, edges }`.
 *
 * - Node ids are `n0`, `n1`, ..., `n(k-1)` for a random `k` in [2, 10].
 * - Edges are drawn from an upper-triangular subset of the id pairs, which
 *   guarantees the result is acyclic (every edge goes from a lower index to
 *   a higher one).
 * - Deduplicated so dagre doesn't receive multi-edges.
 */
const arbDag: fc.Arbitrary<{ nodes: GraphNode[]; edges: GraphEdge[] }> = fc
  .integer({ min: 2, max: 10 })
  .chain((k) => {
    // Upper-triangular pairs (u < v), the full candidate edge set for k nodes.
    const candidates: Array<[number, number]> = [];
    for (let u = 0; u < k; u++) {
      for (let v = u + 1; v < k; v++) {
        candidates.push([u, v]);
      }
    }
    return fc.subarray(candidates).map((chosen) => {
      const nodes = Array.from({ length: k }, (_, i) => makeNode(`n${i}`));
      const edges: GraphEdge[] = chosen.map(([u, v]) => ({
        id: `n${u}->n${v}`,
        source: `n${u}`,
        target: `n${v}`,
      }));
      return { nodes, edges };
    });
  });

describe("Auto-layout places every edge source strictly left of its target", () => {
  it("for every DAG and every edge (u, v), x[u] < x[v]", () => {
    fc.assert(
      fc.property(arbDag, ({ nodes, edges }) => {
        const positioned = autoLayout(nodes, edges);

        expect(positioned).toHaveLength(nodes.length);

        const xById = new Map<string, number>();
        for (const n of positioned) xById.set(n.id, n.position.x);

        for (const e of edges) {
          const xu = xById.get(e.source);
          const xv = xById.get(e.target);
          expect(xu, `missing x for ${e.source}`).toBeDefined();
          expect(xv, `missing x for ${e.target}`).toBeDefined();
          expect(
            (xu as number) < (xv as number),
            `expected x[${e.source}]=${xu} < x[${e.target}]=${xv}`,
          ).toBe(true);
        }
      }),
      { numRuns: 100 },
    );
  });
});
